name: CI

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  haxelib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: krdlab/setup-haxe@master
      with:
        haxe-version: 4.3.7
    - name: Package Haxelib
      working-directory: haxelib
      run: haxe haxelib.hxml
    - uses: actions/upload-artifact@v4
      with:
        name: gtween-haxelib
        path: bin/haxelib/
        if-no-files-found: error

  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: krdlab/setup-haxe@master
      with:
        haxe-version: 4.3.7
    - name: Set up Haxelib dependencies
      run: |
        haxelib install dox --quiet
        haxelib dev gtween ${{ github.workspace }}
    - name: Build API reference
      working-directory: docs
      run: haxe docs.hxml
    - uses: actions/upload-artifact@v4
      with:
        name: gtween-docs
        path: bin/api/
        if-no-files-found: error
    - name: Upload API Reference
      if: ${{ github.repository == 'BowlerHatLLC/gtween-haxe' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
      uses: JamesIves/github-pages-deploy-action@v4.6.0
      with:
        branch: gh-pages
        folder: bin/api
        target-folder: api

  build-swc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: krdlab/setup-haxe@master
      with:
        haxe-version: 4.3.7
    - name: Set up Haxelib dependencies
      run: |
        haxelib dev gtween ${{ github.workspace }}
    - name: Build Flash .swc library
      run: haxe flash.hxml
    - uses: actions/upload-artifact@v4
      with:
        name: gtween-swc
        path: bin/gtween-haxe.swc
        if-no-files-found: error
        
  tests:
    strategy:
      matrix:
        haxe-version: [4.3.7]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: krdlab/setup-haxe@master
      with:
        haxe-version: ${{ matrix.haxe-version }}
    - uses: cedx/setup-hashlink@v6
    - name: Set up Haxelib dependencies
      run: |
        haxelib --global update haxelib --quiet
        haxelib install utest --quiet
        haxelib install hxcpp --quiet
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib dev gtween ${{ github.workspace }}
    - name: Run Tests
      working-directory: tests
      run: |
        haxe interp.hxml
        haxe neko.hxml
        neko bin/tests.n
        haxe hl.hxml
        hl bin/tests.hl
        haxe js.hxml
        node bin/tests.js
        haxe cpp.hxml
        bin/tests/TestsMain-debug
        haxelib run lime test neko

  samples:
    strategy:
      matrix:
        haxe-version: [4.3.7]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: krdlab/setup-haxe@master
      with:
        haxe-version: ${{ matrix.haxe-version }}
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib dev gtween ${{ github.workspace }}
    # --- JS samples ---
    - name: JS GTweenerDemo
      working-directory: samples/js/GTweenerDemo
      run: |
        haxe js.hxml
        mkdir -p ../../gh_pages/js/GTweenerDemo
        cp index.html GTweenerDemo.js ../../gh_pages/js/GTweenerDemo
    - name: JS GTweenInterrupt
      working-directory: samples/js/GTweenInterrupt
      run: |
        haxe js.hxml
        mkdir -p ../../gh_pages/js/GTweenInterrupt
        cp index.html GTweenInterrupt.js ../../gh_pages/js/GTweenInterrupt
    - name: JS GTweenSimpleSequencing
      working-directory: samples/js/GTweenSimpleSequencing
      run: |
        haxe js.hxml
        mkdir -p ../../gh_pages/js/GTweenSimpleSequencing
        cp index.html GTweenSimpleSequencing.js ../../gh_pages/js/GTweenSimpleSequencing
    - name: JS GTweenSpeedDemo
      working-directory: samples/js/GTweenSpeedDemo
      run: |
        haxe js.hxml
        mkdir -p ../../gh_pages/js/GTweenSpeedDemo
        cp index.html GTweenSpeedDemo.js ../../gh_pages/js/GTweenSpeedDemo
    # --- Flash samples ---
    - name: Flash GTweenColorAdjust
      working-directory: samples/flash/GTweenColorAdjust
      run: haxe flash.hxml
    - name: Flash GTweenerDemo
      working-directory: samples/flash/GTweenerDemo
      run: haxe flash.hxml
    - name: Flash GTweenInterrupt
      working-directory: samples/flash/GTweenInterrupt
      run: haxe flash.hxml
    - name: Flash GTweenSimpleSequencing
      working-directory: samples/flash/GTweenSimpleSequencing
      run: haxe flash.hxml
    - name: Flash GTweenSpeedDemo
      working-directory: samples/flash/GTweenSpeedDemo
      run: haxe flash.hxml
    - name: Flash GTweenTimelineDemo
      working-directory: samples/flash/GTweenTimelineDemo
      run: haxe flash.hxml
    # --- OpenFL samples ---
    - name: OpenFL GTweenColorAdjust
      working-directory: samples/openfl/GTweenColorAdjust
      run: |
        haxelib run lime build html5
        haxelib run lime build neko
        haxelib run lime build hl
        haxelib run lime build flash
        mkdir -p ../../gh_pages/openfl/GTweenColorAdjust
        cp -R bin/html5/bin/. ../../gh_pages/openfl/GTweenColorAdjust
    - name: OpenFL GTweenerDemo
      working-directory: samples/openfl/GTweenerDemo
      run: |
        haxelib run lime build html5
        haxelib run lime build neko
        haxelib run lime build hl
        haxelib run lime build flash
        mkdir -p ../../gh_pages/openfl/GTweenerDemo
        cp -R bin/html5/bin/. ../../gh_pages/openfl/GTweenerDemo
    - name: OpenFL GTweenInterrupt
      working-directory: samples/openfl/GTweenInterrupt
      run: |
        haxelib run lime build html5
        haxelib run lime build neko
        haxelib run lime build hl
        haxelib run lime build flash
        mkdir -p ../../gh_pages/openfl/GTweenInterrupt
        cp -R bin/html5/bin/. ../../gh_pages/openfl/GTweenInterrupt
    - name: OpenFL GTweenSimpleSequencing
      working-directory: samples/openfl/GTweenSimpleSequencing
      run: |
        haxelib run lime build html5
        haxelib run lime build neko
        haxelib run lime build hl
        haxelib run lime build flash
        mkdir -p ../../gh_pages/openfl/GTweenSimpleSequencing
        cp -R bin/html5/bin/. ../../gh_pages/openfl/GTweenSimpleSequencing
    - name: OpenFL GTweenSpeedDemo
      working-directory: samples/openfl/GTweenSpeedDemo
      run: |
        haxelib run lime build html5
        haxelib run lime build neko
        haxelib run lime build hl
        haxelib run lime build flash
        mkdir -p ../../gh_pages/openfl/GTweenSpeedDemo
        cp -R bin/html5/bin/. ../../gh_pages/openfl/GTweenSpeedDemo
    - name: OpenFL GTweenTimelineDemo
      working-directory: samples/openfl/GTweenTimelineDemo
      run: |
        haxelib run lime build html5
        haxelib run lime build neko
        haxelib run lime build hl
        haxelib run lime build flash
        mkdir -p ../../gh_pages/openfl/GTweenTimelineDemo
        cp -R bin/html5/bin/. ../../gh_pages/openfl/GTweenTimelineDemo/
    - name: Upload JS Samples
      if: ${{ github.repository == 'BowlerHatLLC/gtween-haxe' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
      uses: JamesIves/github-pages-deploy-action@v4.6.0
      with:
        branch: gh-pages
        folder: samples/gh_pages
        target-folder: samples